const KEY="robom_account_v2";let u=JSON.parse(localStorage.getItem(KEY)||"null");const app=document.querySelector("#app");let gameTimer=null,rewardTimer=null,gameScore=0,gameRunning=false;
function save(){localStorage.setItem(KEY,JSON.stringify(u))}
function stopTimers(){if(gameTimer)clearInterval(gameTimer);if(rewardTimer)clearInterval(rewardTimer);gameTimer=null;rewardTimer=null;gameRunning=false}
function auth(reg=false){app.innerHTML=`<div class="auth"><div class="box"><h1>🎮 Robom Games</h1><p class="sub">${reg?"Создай аккаунт":"Войди в аккаунт"}</p>${reg?'<input id="name" class="input" placeholder="Имя">':""}<input id="email" class="input" placeholder="Почта" type="email"><input id="pass" class="input" placeholder="Пароль" type="password"><button class="btn" onclick="submitAuth(${reg})">${reg?"Зарегистрироваться":"Войти"}</button><button class="link" onclick="auth(${!reg})">${reg?"Уже есть аккаунт? Войти":"Нет аккаунта? Регистрация"}</button></div></div>`}
function submitAuth(reg){const e=document.querySelector("#email").value.trim().toLowerCase(),p=document.querySelector("#pass").value;if(!e||!p)return alert("Заполни почту и пароль");if(reg){if(p.length<4)return alert("Пароль должен быть минимум 4 символа");u={name:document.querySelector("#name").value.trim()||"Игрок",email:e,pass:p,tokens:100,robom:0};save();home()}else{const saved=JSON.parse(localStorage.getItem(KEY)||"null");const old=JSON.parse(localStorage.getItem("robom_account")||"null");const found=(saved&&saved.email&&saved.email.toLowerCase()===e&&saved.pass===p)?saved:(old&&old.email&&old.email.toLowerCase()===e&&old.pass===p)?old:null;if(!found)return alert("Неверная почта или пароль. Проверь раскладку и пробелы.");u={name:found.name||"Игрок",email:found.email.toLowerCase(),pass:found.pass,tokens:Number(found.tokens)||0,robom:Number(found.robom)||0};save();home()}}
function head(){return `<div class="head"><div><b>Привет, ${u.name}! 👋</b></div><div class="wallet"><span class="coin">🪙 Токены: ${u.tokens}</span><span class="coin">💠 Робом: ${u.robom}</span><button class="exchangeBtn" onclick="exchange()">Обмен</button><button class="exit" onclick="stopTimers();u=null;auth()">Выйти</button></div></div>`}
function home(){stopTimers();app.innerHTML=`<div class="wrap">${head()}<h1>Главное меню</h1><p class="sub">Выбирай игру и зарабатывай валюту.</p><div class="grid"><div class="game"><div><h2>🏐 Волейбол</h2><p>После старта каждые 30 секунд +1 Токен.</p></div><button class="btn" onclick="volley()">Играть</button></div><div class="game"><div><h2>⚽ Набивание мяча</h2><p>После старта каждую секунду +1 Токен.</p></div><button class="btn" onclick="kick()">Играть</button></div><div class="game soon"><div><h2>🏀 Баскетбол</h2><p>Новая игра уже готовится.</p></div><button class="btn" disabled>Скоро будет</button></div></div></div>`}
function exchange(){app.insertAdjacentHTML("beforeend",`<div class="overlay" id="ex"><div class="exchange"><h2>💱 Обмен валюты</h2><p>Обменять <b>100 Токенов</b> на <b>1 Робом</b>?</p><p class="small">У тебя: ${u.tokens} 🪙 · ${u.robom} 💠</p><button class="btn" onclick="doExchange()">Обменять</button><button class="link" onclick="document.querySelector('#ex').remove()">Отмена</button></div></div>`)}
function doExchange(){if(u.tokens<100)return alert("Нужно минимум 100 Токенов.");u.tokens-=100;u.robom+=1;save();document.querySelector("#ex").remove();home()}
function volley(){stopTimers();gameScore=0;app.innerHTML=`<div class="wrap play">${head()}<button class="back" onclick="home()">← Меню</button><h1>🏐 Волейбол</h1><div class="status">Счёт: <b id="score">0</b></div><div class="status">🪙 Токенов: <b id="tokens">${u.tokens}</b></div><div class="timer">⏱️ <b id="time">00:00</b></div><button id="start" class="btn" onclick="toggleVolley()">Начать</button><div class="arena"><div class="net"></div><div id="v" class="ball">🏐</div></div></div>`;document.querySelector("#v").onclick=()=>{if(gameRunning){gameScore++;document.querySelector("#score").textContent=gameScore;moveBall()}}}
function moveBall(){const v=document.querySelector("#v");if(v){v.style.left=(Math.random()*80+5)+"%";v.style.top=(Math.random()*65+8)+"%"}}
function toggleVolley(){if(gameRunning){stopGame();return}gameRunning=true;document.querySelector("#start").textContent="Стоп";moveBall();let sec=0;gameTimer=setInterval(()=>{sec++;document.querySelector("#time").textContent=formatTime(sec)},1000);rewardTimer=setInterval(()=>{u.tokens++;save();document.querySelector("#tokens").textContent=u.tokens},30000)}
function stopGame(){stopTimers();const b=document.querySelector("#start");if(b)b.textContent="Начать"}
function formatTime(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function kick(){stopTimers();gameScore=0;app.innerHTML=`<div class="wrap play">${head()}<button class="back" onclick="home()">← Меню</button><h1>⚽ Набивание мяча</h1><div class="status">Счёт: <b id="score">0</b></div><div class="status">🪙 Токенов: <b id="tokens">${u.tokens}</b></div><div class="timer">⏱️ <b id="time">00:00</b></div><button id="start" class="btn" onclick="toggleKick()">Начать</button><div id="b" class="bigball">⚽</div></div>`;document.querySelector("#b").onclick=()=>{if(gameRunning){gameScore++;document.querySelector("#score").textContent=gameScore}}}
function toggleKick(){if(gameRunning){stopGame();return}gameRunning=true;document.querySelector("#start").textContent="Стоп";let sec=0;gameTimer=setInterval(()=>{sec++;document.querySelector("#time").textContent=formatTime(sec)},1000);rewardTimer=setInterval(()=>{u.tokens++;save();document.querySelector("#tokens").textContent=u.tokens},1000)}
u?home():auth();
